---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedestrian-distance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedestrian-distance
  template:
    metadata:
      labels:
        app: pedestrian-distance
    spec:
      containers:
        - name: pedestrian-distance
          image: northamerica-northeast2-docker.pkg.dev/sofe4630/sofe4630u/pedestrian-distance:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pedestrian-distance-service
spec:
  selector:
    app: pedestrian-distance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
---